### PR TITLE
RFC multi pass idea

### PR DESCRIPTION
**Pull request by nopeslide**
this is a refactor attempt to introduce a multi-pass system .
the main goal is to separate feature code and allow to easily introduce new features

in the first pass, a global config is constructed.
in a second pass the cells are generated.

In each pass callbacks can be registered for specific fields (`bitbox`,`annotation`,`bitheader`).
A pass iterates through all fields, annotates fields with an global index as id, and calls the according callbacks.
This minimizing tedious type and value checks.

The first pass generates a global config which can not be modified by the second pass.
The second pass takes this config and similar to the first pass, iterates over all fields and executes callbacks for field types, that generate cells.
A (not implemented) third pass would take the config and all generated cells and map them to table cells.
A third pass may be practical because it can introduce side-effects for cells,

i.e. we have a new feature that introduces gaps 
1. first pass estimates the layout
  - collects information that is handy to have before generating a cell (like pre/post column count) 
2. second pass generates the cells with relative positions,
  - does not need to check other cells, simple code
3. third pass converts relative positions to global ones.  
  - apply position offsets to all cells followed by gap

I would love to see sth like memory maps or other more complex hierarchical stuff like
image
 and I think to make features as easy as possible to integrate may be the way to go here

currently only the provided `test.typ` is working.
most bitheader code was only copied and got just the minimal adjustments 

this PR is based on #12

### CODE REVIEW

**Comment by nopeslide** [comment]
@jomaway please let me know if this idea has some merit

**Comment by jomaway** [comment]
@nopeslide i just had a look at your first draft and it seems like you have similar ideas than i have. 
I just merged #12  and some of my local changes (wasn't that easy to combine everything). 

In my changes i already did some refactoring towards a pass system. Currently few things are still bothering me. 
The `bitheader` can be alot of different types and some combinations of `smart` and `msb_first` don't make to much sense right now. I think we need to figure out a good user API for this and some internal representation similar to `bitbox` and `annotation`. Maybe we can use the current `dict` version and add a `type` field which contains `custom` or `bounds` or `small`.  Don't know yet. 

Another thought i had on **annotations**: Maybe it would simplify things if we always only use one column for pre annotations and one for post annotations and then add a subgrid for multiple levels. This would make it possible to drop `pre` and `post` len calculations or at least keep them to their local changes. Maybe this will complicate things like groups. Not sure yet. 

Anyway your ideas are always welcome. :+1:

**Comment by nopeslide** [comment]
> Another thought i had on **annotations**: Maybe it would simplify things if we always only use one column for pre annotations and one for post annotations and then add a subgrid for multiple levels. This would make it possible to drop `pre` and `post` len calculations or at least keep them to their local changes. Maybe this will complicate things like groups. Not sure yet.

this would make overlapping annotations quite hard, because they would need emulated rowspans over multiple grids

**Comment by nopeslide** [comment]
> The `bitheader` can be alot of different types and some combinations of `smart` and `msb_first` don't make to much sense right now. I think we need to figure out a good user API for this and some internal representation similar to `bitbox` and `annotation`. Maybe we can use the current `dict` version and add a `type` field which contains `custom` or `bounds` or `small`. Don't know yet.

@jomaway 
I played a little with the bitheader interface, I think you will like it.
The most important change was the massive use of positional arguments.
This makes the interface slim and you get a feeling of a "smart" interface, that allows mixing arguments without deeper knowledge.
Every bitheader argument has a different type now, and can simply be listed.
check the examples 

The only thing I'm not quite happy with is the true/false for showing just labels or labels with numbers, because it is a global option and not settable for single bits
How about negative numbers to explcitiy not show a number?
This would be just the shorthand version of specifying a parameter with a list of numbers to not show (which must be used to omit the zero)  
`bitheader(true, 1:[bit 1], -1)` is the same as `bitheader(false,1:[bit 1])` 
`bitheader(0,1,2,-1)` is the same as `bitheader(0,2)` or `bitheader(0,1,2, omit:(1,))` 
furthermore things like `"-all"` or "-smart" can also be possible.
you want labels without numbers? easy enough `bitheader(0,[bit 0],1,[bit 1],"-all")`

**Comment by nopeslide** [comment]
@jomaway 
your annotation implementation is doing something completely different.
it just stuffs annotations from the top down,
my implementation annotated the current row of fields in the table

**Comment by jomaway** [comment]
> @jomaway your annotation implementation is doing something completely different. it just stuffs annotations from the top down, my implementation annotated the current row of fields in the table

Yeah that's true, as in my changes the fields aren't processed in an linear order this was kind of hard to get right and it was already getting late. I guess this can be fixed in several ways. 
- First is to enumerate all incoming fields and calculate the position from that index. 
- Second is to change layout of annotations completely.

But i am not sure if the first method or the way it was handled in your PR can cover every edge case. 
If we want to define where a note is "rendered" an approach would be to say: A `annotation` corresponded to the same row as the following `bitbox`  on the left side and on the previous `bitbox` on the right side.

Anyway i would like to have some sort of API to set the position of an annotation explicitly. So it can be defined anywhere in the bytefield. This probably needs a bit more calculation as there can be multiple cells at the same place. 

I want to play with some different approaches and then we will see which is the best option to go with.

**Comment by jomaway** [comment]
> The only thing I'm not quite happy with is the true/false for showing just labels or labels with numbers, because it is a global option and not settable for single bits How about negative numbers to explcitiy not show a number? This would be just the shorthand version of specifying a parameter with a list of numbers to not show (which must be used to omit the zero) `bitheader(true, 1:[bit 1], -1)` is the same as `bitheader(false,1:[bit 1])` `bitheader(0,1,2,-1)` is the same as `bitheader(0,2)` or `bitheader(0,1,2, omit:(1,))` furthermore things like `"-all"` or "-smart" can also be possible. you want labels without numbers? easy enough `bitheader(0,[bit 0],1,[bit 1],"-all")`

This looks like an idea which we can work on. I would suggest mixing positional arguments with named arguments for example the true/false for numbers. Actually `msb_first` is also only for the header so we can have a named argument `msb:true` .

Another thing I am not really happy with is that “smart“ and “bounds“ show offsets for fields which are in the second or third line. Which doesn‘t make much sense in my opinion. But I would like to know what you think about that?

If we think what a `header_cell` will contain then I come up with:
- `position` which indicates the x - offset from bit 0.
- `number` which represents the number. Same as `position`  if `msb:false`  and  `row_width - 1 - position` if `msb:true` 
- `label` which is a text representation or description.

Each cell can show the number and/or the label.


Another question is if we want to support headers between rows I the future and how to handle this also in combination with annotations. And what about annotations above or below. An use case could be to group two fields together and show this with a bracket and note below them.

**Comment by nopeslide** [comment]
@jomaway  

some thoughts

regarding grid positions
I think it makes sense if we completely build our own placement system and map this at the end to to tablex placements.
fundamentally, we have a grid with bits in the middle, surrounded by annotations.
we can divide our global grid in multiple subgrids: center/left/right/top/bottom
a cell can only be positioned in one of these subgrids.
i.e. a bitcell has a position in the center, a left-sided annotationcell in the left, ...
(I would put bitheaders also into the center, because this enables multiple bitheader for multirow representations of large registers.)
specifying a position could look like this
```typst
let first_bit_cell = (
  type:"bitcell",
  pos: (
    center: (0,0)
  )
)
```
now we can differentiate between different grids instead of types of cells
since multiple cell types may occupy the same grid

regarding IDs
i propose each element has a unique id.
we can use an index series as unique id.
since we start with fields, which are expanded to cells, which are expanded/mapped to table cells,
we automatically generate a unique index series for each element.
the series even reflects the elements origin, making debugging tasks simpler.

regarding left/right annotations:
i propose the convention: annotations are always annotating fields that come after them.
instead of calculating their position themselves, they could refer to the field coming after them in a later pass
i.e. copy the row of the next cell that has a center position

**Comment by nopeslide** [comment]
> Another thing I am not really happy with is that “smart“ and “bounds“ show offsets for fields which are in the second or third line. Which doesn‘t make much sense in my opinion. But I would like to know what you think about that?

This was my intention, so the ranges of later fields are shown indirectly.
But i see your point, maybe we should add variants which only cover the next lines, or even better, only up until some kind of `break` or `gap` field


> Another question is if we want to support headers between rows I the future and how to handle this also in combination with annotations. And what about annotations above or below. An use case could be to group two fields together and show this with a bracket and note below them.

haha we had a lot of same thoughts.

**Comment by jomaway** [comment]
> regarding grid positions I think it makes sense if we completely build our own placement system and map this at the end to to tablex placements. 

Totally agree with you on this point. 

> fundamentally, we have a grid with bits in the middle, surrounded by annotations. we can divide our global grid in multiple subgrids: center/left/right/top/bottom a cell can only be positioned in one of these subgrids. 

That's kind of in the same direction what i suggested earlier on with setting only one column left and right for annotations in the main grid and use subgrids there.

> regarding IDs i propose each element has a unique id. 

Just implemented this to fix the annotation positioning. (_Related to https://github.com/jomaway/typst-bytefield/issues/13#issuecomment-1939247415_)

> regarding left/right annotations: i propose the convention: annotations are always annotating fields that come after them. instead of calculating their position themselves, they could refer to the field coming after them in a later pass i.e. copy the row of the next cell that has a center position

Still not sure if this is the most obvious way, but i kept it that way for now. 

@nopeslide  FYI doing some more refactoring the next days and then you can start adding new features again without the code diverging to much from each other.

**Comment by nopeslide** [comment]
> FYI doing some more refactoring the next days and then you can start adding new features again without the code diverging to much from each other.

I think we should separate metadata/config and fields even more.
It was a delight to have a single metadata/config object as single truth in this PR for debugging and testing purposes.
when we separate metadata/config generation and cell generation in different functions, we can test each individually.
This would make testing and debugging a blaze (i outputted the metadata/config and rendered output as 2 columns in my dev setup)
I think of something like
```typst
let bytefield(args, fields) = {
  let meta = generate_meta(args, fields)
  let cells = generate_cells(meta, fields)
  let table = generate_table(meta, cells)
  return table
}
```

edit:
we can separate fields by listing their id in a specific type or grid field in the meta/config.
this would look sth like this.
```typst
let meta = (
  types: (
    bitbox: (1,2,4),
    annotation: (3,),
    bitheader: (0,)
  ),
  grid (
    center: (0,1,2,4),
    left: (3,),
  )
)
```

**Comment by nopeslide** [comment]
regarding our placement
it could be practical to have special grid variable that holds the various grids and a mapping from positions to cell ids.
this would essentially be the final layout.
```typst
let grid = (
  center: (
    "(0,0)":0,
    "(1,0)":1,
    ...
  ),
  left: ( ... ),
  ...
)
```
this would make a neighbor search trivial, which we need when we are tackling borders.
and even more important, could warn us of any layout problems way before tablex,
which would allow us to annotate any errors and generate sexy debug stuff like mapping ids into a visual grid

image

**Comment by jomaway** [comment]
@nopeslide i just merged my part of the refactor and some of your ideas (like the new bitheader api)  into main. See #16 . It still has some rough edges and room for improvements, but i guess it is better than before. Some things like the multiple subgrids are not implemented yet, but steps are taken that should make it not to difficult to add this later on. 

I guess priority is to clean up the new bitheader api and release version 0.0.4 to make the improvements with annotations available to everyone. 

I also will close this PR as i guess it is better to move discussions to related issues.

**Pull request closed without merging**
